language: csharp
dist: trusty
sudo: false

mono: none
dotnet: 2.1.3

install:
  - dotnet restore

script:
  - dotnet build -c Release
  - dotnet test -c Release src/WakeOnLan.Tests/WakeOnLan.Tests.csproj

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: src/WakeOnLan/bin/Release/*.nupkg
    skip_cleanup: true
    on:
      branch: master
      tags: true

    # TODO: Deployment to NuGet
